### ISSUE TITLE
[BUG] Umbra does not respect Dalamud's Font Scaling setting

### ISSUE THREAD

**Issue by gsapi** [una-xiv/umbra#10]
Hello! I play on a 4k display and use 150% Global Font Scale in Dalamud's settings. Unfortunately this makes the Umbra UI look very cramped as it does not resize to match the text:

![image](https://github.com/una-xiv/umbra/assets/124498640/d7f55c4b-e4d3-4731-be25-3854298695f8)
![image](https://github.com/una-xiv/umbra/assets/124498640/eaa246ff-9324-4579-b114-1f6db266dac1)

I hope it's possible to fix this somehow! Thank you 🙂

**Comment by haroldiedema** [comment]
Hey, thanks for the report!

Font scaling isn't something I've focused on so far since it not only affects font size, but element size as well if done right. I'll add it to my to-do list to look at later.

**Comment by Nox13last** [comment]
I know the ticket is "resolved as planned", but I'd like to add my vote for demographic reasons.
As a 4K user, I gotta squint real good in order to make out the text. Also, with regard to the element size, that could also stand to be increased. I turned on "point towards unacquired TT cards", and if I weren't already playing Air Force One (where the camera whips about, and would move the icon a lot), I would not have seen it.

It's a gorgeous plugin, though.
