### ISSUE TITLE
[Bug] Crafters don't fit within gearset widget

### ISSUE THREAD

**Issue by Noaburr** [una-xiv/umbra#101]
There are 8 crafting classes, but the gearset list only shows 7 (assuming all crafters and gatherers have gearsets). In my case the Leatherworker gearset is missing.

If space is an issue, a toggle to remove headers (Tank, Healer, Physical, Physical Ranged, Magical Ranged, Crafter & Gatherer) would likely allow all DoL/DoH gearsets to fit in a single column, since they are already distinguishable by color.

![image](https://github.com/una-xiv/umbra/assets/85835804/de72715e-b194-4889-ad9e-4ba6f08e1e70) ![image](https://github.com/una-xiv/umbra/assets/85835804/9a61dfb9-85b1-4dcb-9827-6dcd20357fcf)

**Comment by haroldiedema** [comment]
You can define the height of each category in the settings. If they don't fit, you should be able to scroll in the containers. Just hover the category with your mouse and use the scrollwheel if you can't see the scrollbar itself.

This has been made a lot more clear in the new 2.0 version, with some extra customization, including what you're suggesting about hiding the header labels 😄 

Here's what that looks like in action:
![image](https://github.com/una-xiv/umbra/assets/567518/8e1b2a2a-b7d3-4f34-b5d7-a392c7f96c9f)

I'm going to close this, as it is already fixed.

The new 2.0 release is currently in review, but since it's a large update, it will take a while before it gets merged into Dalamud's official repo itself.
