### ISSUE TITLE
[Feature Request] Register a text command that duplicates the flag widget's onClick

### ISSUE THREAD

**Issue by HawkAtreides** [una-xiv/umbra#108]
I haven't found any other plugin with a "teleport to current flag" feature, as opposed to "teleport to the Aetheryte hard-coded for this specific target, and being able to invoke that functionality via text command would be useful for controller users. So the use case would be:

1. Flag is generated by some means
2. Umbra sets flag widget to current flag and enables teleporting
3. /umbra-tp (or whichever other text command is registered) is invoked
4. Umbra starts the same teleport sequence used by the widget

**Comment by haroldiedema** [comment]
This functionality is closely tied to the flag widget itself and seeing as the system allows multiple instances of it to exist, it would clash with the command registration system of Dalamud. Simultaneously this means that not having the widget on the toolbar, would effectively break the functionality of the command.

I'm going to have to decline implementing this, since it'll likely cause unexpected behavior for users that is hard to explain.

**Comment by HawkAtreides** [comment]
Understandable! Honestly I should've closed this out myself at the transition to v2.
