### ISSUE TITLE
[Feature request] A custom menu (popup) where I can put custom buttons in

### ISSUE THREAD

**Issue by mehistaken** [una-xiv/umbra#125]
I have a bunch of custom macros general aesthetics stuff like mounts and fashion accessories for different job/locations.

It would be nice to have a popup menu like the system ones to group these in.

**Comment by Doresain** [comment]
+1 to this request.

Stipulating that:
1. This plugin is already awesome as hell, thank you!
2. This is def a nontrivial ask.

My first thought was "Man, this is great. I wonder if I can make custom menus like these for the main menu? Then I could get rid of QoLBar!" So yeah. Lets just shove QoLBar functionality (another very complex plugin) into your plugin. No big deal, right? :D

**Comment by haroldiedema** [comment]
Yes, this is easily solved using QoLBar and a custom button that toggles the visibility of your custom QoLBars.

As for this being a non-trivial task: Widgets in Umbra have a static set of configuration options. Adding something like this _will_ result in a large list of config options for a fixed amount of menu entries, rather than it being a "list" in which you can add items. The system just isn't designed for those types of widgets.

Since I'm trying really hard to find a balance on what to implement and what not to implement, and trying to go with the thought of _not_ turning Umbra into an omni-plugin entirely, I'm putting this on low priority for now, especially since there is a perfectly suitable workaround that encourages users being creative using multiple plugins.

I'll also update the README of this repository regarding feature requests to try and give a bit more clarity on these types of things.
