### ISSUE TITLE
[Feature Request] Separate Top and Bottom bars at the same time

### ISSUE THREAD

**Issue by mkolassa** [una-xiv/umbra#128]
As someone who loves utilizing info bars in World of Warcraft, it would be awesome to have the ability to have both a top and bottom bar at the same time, that way we can spread stuff out a bit.

**Comment by haroldiedema** [comment]
Heya!

I appreciate the request, but I'm going to have to turn this down for the forseeable future. This would involve a _lot_ of refactoring in the current architecture. Seeing as how long it took for Umbra v2 to get accepted in the official Dalamud repositories, I'm afraid that an update of this size would delay updates for too long due to the strict review process.

Maybe we can do this sometime down the road, but I don't see this happening in the forseeable future.
