### ISSUE TITLE
[Feature Request] - Aethercurrent World Markers

### ISSUE THREAD

**Issue by KalChoedan** [una-xiv/umbra#137]
I don't believe this steps on the toes of any existing plugins and I think it fits the rest of the guidelines. 

There are actually a couple of additional World Marker types that would be useful - Aethercurrents was the one that struck me first (having discovered Umbra while I'm still levelling through Dawntrail!) But World Markers for Sightseeing log entries could be very handy too.

**Comment by haroldiedema** [comment]
This one will take some time because of stuff that needs figuring out. Namely testing whether Aether Currents have already been unlocked or not. And preferably not having them show up in unexplored areas to prevent giving spoilers while progressing through the MSQ.

I'll see if I can cook something up that adheres to this and if Dalamud / CS actually exposes this information. No promises though.

**Comment by haroldiedema** [comment]
Fixed for 2.1.10
