### ISSUE TITLE
[Feature request] Hide Main Menu buttons

### ISSUE THREAD

**Issue by NotNite** [una-xiv/umbra#181]
Right now Umbra overlaps my menu buttons:

![image](https://github.com/user-attachments/assets/19569d7e-1d8b-4830-bcf2-43be7a41a37e)
![image](https://github.com/user-attachments/assets/f38b044b-c7a4-49c5-9412-1faf1d5b8fe2)

Would be nice to hide the game ones automatically when the plugin is enabled.

**Comment by haroldiedema** [comment]
This is very widget-specific. Since the main menu isn't a single widget like the server info bar, this would entail having a global setting to hide the main menu for as long as Umbra is active. But what if it's active and there are no main menu button widgets?

Seeing as how confusing this may become to people, I'm not going to implement this.
