### ISSUE TITLE
[Freature Request] - Teleportation pop-up menu, anchor point option or constant width

### ISSUE THREAD

**Issue by billy-lack** [una-xiv/umbra#204]
[Freature Request] - Teleportation pop-up menu, anchor point option or constant width.
This would be a very nice feature, because that would in turn mean that you have so that the category menu is always in the same place, no matter how many columns of aetherytes there are in the list.
As it is now, the categories move around quite a lot when you change them.

**Comment by haroldiedema** [comment]
This only happens when you have the widget in the center column, since popups are then centered on the widget. This is by design.

However, you can mitigate this already by creating a fixed width by using the "Minimum columns to display" option.
![image](https://github.com/user-attachments/assets/fbd02486-b8d2-42af-9474-21a25c4e1798)
