### ISSUE TITLE
[Feature Request] (Un)muting individual sound channels in the volume mixer

### ISSUE THREAD

**Issue by gsapi** [una-xiv/umbra#27]
I think it'd be neat if we could quickly mute/unmute a singular audio channel, similar to toggling via text command eg. `/bgm`. Perhaps by clicking the `BGM x%` label, or adding a mute/unmute button beneath each slider?

**Comment by haroldiedema** [comment]
I've been looking for this feature in Dalamud to see if there is something that I could use "out of the box". Unfortunately implementing this would require some use of custom signatures, which I would very much like to avoid as much as possible, since these may be rather sensitive to break between game patches/updates.

I'll implement this once there is a ready-to-use method in Dalamud that I can hook into.

**Comment by haroldiedema** [comment]
Found a way to implement this.

https://github.com/goatcorp/Dalamud/blob/c2250295552f661335d77ee637cb2d7fc217fb27/Dalamud/Game/Config/SystemConfigOption.cs#L1188-L1235
