### ISSUE TITLE
[Bug] Gearset Switcher widget text obscured with increased default font size

### ISSUE THREAD

**Issue by shaibalmuhtadee** [una-xiv/umbra#301]
## Increased default font size to 3.000
![image](https://github.com/user-attachments/assets/10fc0407-8a04-4aa1-8c11-1437b8da5946)
## Clipping on job level subtext
![image](https://github.com/user-attachments/assets/ed5482ae-f1f0-4328-aa2d-b881cf710872)

There are no settings in the [widget configuration menu](https://github.com/una-xiv/umbra/blob/main/Umbra/src/Toolbar/Widgets/Library/GearsetSwitcher/GearsetSwitcherWidget.Config.cs) to adjust the text size and offset for the text in each role container.

**Comment by haroldiedema** [comment]
This isn't really a bug but how the size offset works globally in the entire plugin.

The size of elements the text is rendered in, isn't increased when modifying the font size offset. Rather, this setting is meant for fonts that are either too big or too small compared to other "regular" fonts. 

This issue can be fixed by adding height options to the gearset switcher widget.
