### ISSUE TITLE
[Feature Request] Able to pick the colors of the system menu bottons

### ISSUE THREAD

**Issue by Ellarisa** [una-xiv/umbra#68]
Hi would there possible be an option to add a color picker to the system menu bottons? Or have an option to turn the buttons dark instead of red like this for an example https://imgur.com/ECCNb9n

**Comment by haroldiedema** [comment]
If you have the option to show icons instead of labels enabled, Umbra simply picks the icons from the game. If you have modded icon packs installed (via Penumbra for example), it will use those instead.

Do note however that the icons you normally see in the MainCommand HUD element of the game itself has a different set of icons, because it's a single texture internally. Umbra just uses regular icons.

I'm dabbling with the idea of adding separate widgets for individual system menu buttons that may have some custom styling options - along side the regular Main Menu widget - for people that only want to use _some_ buttons or rearrange them. I think I can add some styling options to those as well.

**Comment by Ellarisa** [comment]
that sounds good

**Comment by haroldiedema** [comment]
The upcoming 2.0 release will allow you to add separate widgets per system menu category. Each of these have a ton of customization options.

![image](https://github.com/una-xiv/umbra/assets/567518/01733baf-af31-42c6-8931-a647ee76db0e)
![image](https://github.com/una-xiv/umbra/assets/567518/d6c64327-6ffc-4fbf-bbd8-ff9de84a8858)
![image](https://github.com/una-xiv/umbra/assets/567518/122f0003-7765-4e8b-8c36-72fe4a59181c)
