### ISSUE TITLE
[Feature Request] server info bar spacing

### ISSUE THREAD

**Issue by Megagalatkikarea2** [una-xiv/umbra#90]
let us decrease or increase the server info bar spacing

**Comment by Megagalatkikarea2** [comment]
and while we're at the topic of info bar:
show the status of run/walk like the normal one does

**Comment by haroldiedema** [comment]
Item spacing is fixed in the upcoming 2.0 release.
![image](https://github.com/una-xiv/umbra/assets/567518/554325a3-fbc5-426b-aef7-d8247ebdd530)

I have yet to find a way to determine whether the character walking or running. The server info bar of Umbra only shows entries from other plugins, rather than everything from the game itself. That being said, the one you're asking for will be a separate widget, once I've figured out how to grab the necessary information from the game.
