### ISSUE TITLE
[Feature Request] Parameters on toolbar

### ISSUE THREAD

**Issue by wllpwr** [una-xiv/umbra#94]
Would be nice to have health / MP, possibly even limit gauge as a widget for Umbra, I like having this info at the bottom and having it integrated into the toolbar would be a great touch.

**Comment by haroldiedema** [comment]
Elements that deal with combat info is not something I'm planning on implementing, since that will open the door to a ton more feature (requests) while Umbra is already extremely big as it is.

I suggest using DelvUI for the parameter bars. It's highly customizable so you can make that look like it's one coherent interface together with Umbra
